clean:
	find . -name '*.pyc' -exec rm --force {} + 
	find . -name '*.pyo' -exec rm --force {} +
	find . -name 'a.out' -exec rm --force {} +
	find . -name 'results' -exec rm --force {} +
run:
	python run_synthesis.py